### ISSUE TITLE
Error when running docker-compose build

### ISSUE THREAD

**Issue by oren** [serdmanczyk/Freyr#1]
```
ERROR: Couldn't find env file: /home/oren/p/Freyr/.env
```

Is that's the correct way to run the project? Also the demo page (https://freyr.erdmanczyk.com/latest) shows no data.

**Comment by serdmanczyk** [comment]
The docker-compose files point to the .env files to load environment variables that the containers use for configuration (expository, you may already know that).  I didn't include those on purpose since they're sensitive data, but I could include .sample_envs so you know what to configure...  I'll add those.

I wouldn't say there's a 'correct' way to run but you're on the right path.  You have to build go, the surtr cli, and [webpack](https://webpack.github.io/) ReactJS separate from running Docker-Compose.  There's example commands in the Makefile so you just have to run e.g. `make freyr` or `make surtr` to compile the go code inside a container.  I haven't containerized running webpack yet, so you'd have to install that.  There's already a compiled bundle.js, so you'd only need webpack as soon as you decided you wanted to make changes to the frontend.  Other than that, yeah, it's just docker-compose and there's examples of using the different compose files in the Makefile.

As for the demo page, it looks like if you navigate to /latest without being logged in it shows empty rather than prompting login, I think that counts as another bug to fix.  Simple workaround for now is to navigate back to / then login.

**Comment by oren** [comment]
Thanks! it would be fantastic to have a step by step 'how to run the project' in the Readme. If you don't add it i'll try to figure it out.

**Comment by serdmanczyk** [comment]
Sure!  I hadn't added one yet since I didn't know there would be demand.  I'll see if I can get a basic 'getting started' in the next few days.

**Comment by oren** [comment]
Go + React is a nice combo. I am sure many others will enjoy learning this repo.

**Comment by serdmanczyk** [comment]
I added a how-to in the readme + a configuration to simplify some of the get up and running steps.  Let me know how it goes!

**Comment by oren** [comment]
sweet. thank you!
